import "./globals.css";


export const metadata = {
  title: "Arqen",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`} suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
